modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Othlon/CherryPig/issues"
license="All rights reserved"

[[mods]]
modId="cherrypig"
version="${file.jarVersion}"
displayName="CherryPig"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cherrypig"
logoFile="bigpig.png"
authors="Othlon"
credits="everyone who helped me out <3"
description='''Dem Piggies of teh cherry variety! Now coming to a world near you.'''